name: Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências do Python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script Python
        env:
          URL: ${{ secrets.URL }}
          URL_A: ${{ secrets.URL_A }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          LANG_COUNTRY: ${{ secrets.LANG_COUNTRY }}
          WALLET: ${{ secrets.WALLET }}
          TOKEN1: ${{ secrets.TOKEN1 }}
          TOKEN2: ${{ secrets.TOKEN2 }}
          TOKEN3: ${{ secrets.TOKEN3 }}
          TOKEN4: ${{ secrets.TOKEN4 }}
          TOKEN5: ${{ secrets.TOKEN5 }}
          TOKEN6: ${{ secrets.TOKEN6 }}
          TOKEN_A1: ${{ secrets.TOKEN_A1 }}
        run: |
          python app.py || echo "⚠️ app.py falhou"
          echo ""
          echo ""
          echo "========== Outro app =========="
          echo ""
          python app2.py
        
      - name: Fazer upload da captura de tela
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screen.png
